/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


DROP PROCEDURE IF EXISTS `debug_begin`;
DELIMITER //
CREATE PROCEDURE `debug_begin`()
BEGIN
	IF EXISTS (SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME = 'debug' AND TABLE_SCHEMA = DATABASE()) THEN
		DROP TABLE debug;
	END IF;
	 
	CREATE TABLE debug (
		msg VARCHAR(255),
		var VARCHAR(255),
		value VARCHAR(255))
	ENGINE = MEMORY; 
END//
DELIMITER ;


DROP PROCEDURE IF EXISTS `debug_msg`;
DELIMITER //
CREATE PROCEDURE `debug_msg`(IN `a_msg` varchar(255))
BEGIN
	IF EXISTS (SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME = 'debug' AND TABLE_SCHEMA = DATABASE()) THEN
		INSERT INTO debug (msg, var, value)	VALUES(a_msg, '', '');
	END IF;
END//
DELIMITER ;


DROP PROCEDURE IF EXISTS `debug_show`;
DELIMITER //
CREATE PROCEDURE `debug_show`()
BEGIN
	IF EXISTS (SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME = 'debug' AND TABLE_SCHEMA = DATABASE()) THEN
		SELECT * FROM debug;
		DROP TABLE IF EXISTS debug;
	END IF;
END//
DELIMITER ;


DROP PROCEDURE IF EXISTS `debug_var`;
DELIMITER //
CREATE PROCEDURE `debug_var`(IN `a_var` varchar(255), IN `a_value` varchar(255))
BEGIN
	IF EXISTS (SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME = 'debug' AND TABLE_SCHEMA = DATABASE()) THEN
		INSERT INTO debug (msg, var, value)	VALUES('', a_var, a_value);
	END IF;
END//
DELIMITER ;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
